module.exports = [
  {
    name: "Bottled Water",
    category: "food",
    price: 400,
    average_shelf_life: "3 years",
    expiration_date: "21220222",
  },
  {
    name: "Duct Tape",
    category: "household",
    price: 700,
    average_shelf_life: "7 years",
    expiration_date: "20220222",
  },
  {
    name: "Potato Chips",
    category: "food",
    price: 500,
    average_shelf_life: "3 months",
    expiration_date: "21220222",
  },
  {
    name: "Band-Aids",
    category: "first-aid",
    price: 800,
    average_shelf_life: "5 years",
    expiration_date: "20220222",
  },
  {
    name: "Batteries AAA",
    category: "household",
    price: 2000,
    average_shelf_life: "10 years",
    expiration_date: "21220222",
  },
  {
    name: "Carbon Monoxide Detector",
    category: "household",
    price: 5000,
    average_shelf_life: "4 years",
    expiration_date: "20220222",
  },
  {
    name: "Sunscreen",
    category: "personal",
    price: 1200,
    average_shelf_life: "1 year",
    expiration_date: "21220222",
  },
  {
    name: "Aspirin",
    category: "first-aid",
    price: 700,
    average_shelf_life: "2 years",
    expiration_date: "20220222",
  },
  {
    name: "Milk",
    category: "food",
    price: 500,
    average_shelf_life: "3 days",
    expiration_date: "21220222",
  },
  {
    name: "Toothpaste",
    category: "personal",
    price: 600,
    average_shelf_life: "6 years",
    expiration_date: "20220222",
  },
  {
    name: "Carrots",
    category: "food",
    price: 300,
    average_shelf_life: "1 month",
    expiration_date: "21220222",
  },
];
